server.servlet.context-path=/api

# Configuration JWT
jwt.secret-key=327d8f9b2c4e5a6s7c8d9e0f1a2b3c4dçe6f7a8b9c0d1e2f3a4b5d6d7e8f9a0b
# Durée de validité du Token (1 heure)
jwt.expiration=3600000

# bdd H2
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=gaci
spring.datasource.password=gaci
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Configuration Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs